### ISSUE TITLE
Selected Game Indicator Missing

### ISSUE THREAD

**Issue by Unknow0059** [Deytron/SteamNite#21] opened 2020-07-18 06:28 UTC
![Playnite Comparison_gAQ_071820-03h06m23s](https://user-images.githubusercontent.com/25656892/87846148-01496380-c8a4-11ea-8700-9108f4cea6ce.png)

Left/Right respectively: Tweaked Dark, SteamNite.

I cannot tell which game(s) I have selected because there is no border around them indicating so.

This is a bit of a deal-breaker for me.

**Comment by Deytron** [comment] 2020-10-13 07:47
Duplicate of #19

**Closed as completed by Deytron** 2020-10-13 07:47 UTC
